### ISSUE TITLE
Reposition popover when the content inside the popover changes

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#13]
Here is the scenario, you have a list with a filter inside of it
![screen shot 2018-06-12 at 16 01 44 pm](https://user-images.githubusercontent.com/32653716/41321803-6ce20788-6e5a-11e8-848f-809063bcf08a.png)

Now you start to filter on it
![screen shot 2018-06-12 at 16 04 46 pm](https://user-images.githubusercontent.com/32653716/41321806-7273894c-6e5a-11e8-98a6-98e7dc1e7ed5.png)

Here is the first issue, clearly the popover and the target do not reposition next to one another. Finally when you try to click on the item it actually does move but the item isn't selected
![screen shot 2018-06-12 at 16 04 51 pm](https://user-images.githubusercontent.com/32653716/41321825-8eeb0640-6e5a-11e8-879c-7178c44f84c3.png)

This results in a very jarring experience.

**Comment by k2snowman69** [comment]
Should be resolved with 0.5.0!
