### ISSUE TITLE
Initial position seems to be off

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#20]
On first load sometimes the popover seems to be positioned incorrectly and then on scroll or resize it positions correctly. Trying to figure out how to create a demo...

**Comment by k2snowman69** [comment]
This sounds familiar to a previous but we had but if you get a reproduction going let us know and we can take a look.

**Comment by k2snowman69** [comment]
I remember now! It had to do with our old styles and the way we positioned the arrow. Instead now we just use the border to denote the arrow which helped a ton. You can grab the new styles from here and the switch should only take about 15 minutes per Popover. Let us know if we can help further!
https://github.com/snowcoders/react-popover/blob/master/src/styles.scs

**Comment by rickyp-uber** [comment]
Yep, thanks!
