### ISSUE TITLE
Component should reposition if the content inside changes size

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#23]
This did work before 1.1.0 but seems to not work anymore...

**Comment by k2snowman69** [comment]
We removed it due to build issue complaints... we will add it back once whatever the issue was is sorted out. We will use this issue to track the work.

**Comment by k2snowman69** [comment]
Just to note, we only disabled this for React 15. React 16 still has this functionality.

**Comment by k2snowman69** [comment]
1.1.4 :-)
