### ISSUE TITLE
Clean up build output

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#27]
The build output has multiple js files and is a bit big... if you integrate webpack with this starting config it should get you going
[webpack.config.js.txt](https://github.com/snowcoders/react-popover/files/2255583/webpack.config.js.txt)

**Comment by k2snowman69** [comment]
Just released `1.1.4-alpha.1` so that you can give this a try and see how it works for you!

**Comment by k2snowman69** [comment]
1.1.4
