### ISSUE TITLE
Move away from using document listeners

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#32]
When using a document listener for the "blur" popover type, if an element consumes an event but stop propagation, the dropdown won't be dismissed when that element is clicked.

**Comment by k2snowman69** [comment]
Though I don't disagree that a document listener is a bad idea is there a different solution to the problem you would suggest?

**Comment by k2snowman69** [comment]
Researching this a bit, this is also the solution that jquery-ui has gone with as well
https://github.com/jquery/jquery-ui/blob/master/ui/widgets/selectmenu.js#L421

I'm going to close this out but feel free to comment if you think you may have come up with a better solution
