### ISSUE TITLE
React warning thrown from Popover

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#7]
warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Popover`. See https://fb.me/react-warning-keys for more information.
    in TargetHover (created by Popover)
    in Popover (created by Tooltip)

**Comment by k2snowman69** [comment]
This is probably due to the following code for React 15 backwards compatibility
```
// React 15 will have to pass a element to wrap everything inside of
let wrapperElement = React.createElement(
    this.props.wrapperElementType,
    this.props.wrapperElementProps,
    [
        this.renderTarget(),
        this.renderPopper()
    ]);
```

So if you set the key on your renderTarget and renderPopper, you should be set!

**Comment by k2snowman69** [comment]
Closing issue, feel free to re-open if it is still a problem

**Comment by rickyp-uber** [comment]
Tried that... Doesn't work. Still getting the same error...
